""""
runtime error is the error in which the error is logical means logically we need to correct them it is not generated by
syntex
"""
#a = 1
#b = "kamal"
#print(a+b)

"""
so the above one is the error is called the runtime error example 
"""